# Generated by Django 6.0.4 on 2026-05-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_messages", models.IntegerField(default=0)),
                ("total_members", models.IntegerField(default=0)),
                ("device_type", models.CharField(default="unknown", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("sender", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_media", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("emoji_count", models.IntegerField(default=0)),
                ("has_link", models.BooleanField(default=False)),
                ("day", models.CharField(max_length=20)),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("hour", models.IntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="analyzer.chatsession",
                    ),
                ),
            ],
        ),
    ]
